/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Alterian.JO.Client;
using Alterian.JO.Api;
// uncomment below to import models
//using Alterian.JO.Model;

namespace Alterian.JO.Test.Api
{
    /// <summary>
    ///  Class for testing LicenseApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LicenseApiTests : IDisposable
    {
        private LicenseApi instance;

        public LicenseApiTests()
        {
            instance = new LicenseApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LicenseApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LicenseApi
            //Assert.IsType<LicenseApi>(instance);
        }

        /// <summary>
        /// Test LicenseClientActiveGet
        /// </summary>
        [Fact]
        public void LicenseClientActiveGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string varClient = null;
            //var response = instance.LicenseClientActiveGet(varClient);
            //Assert.IsType<LicenseList>(response);
        }

        /// <summary>
        /// Test LicenseClientGet
        /// </summary>
        [Fact]
        public void LicenseClientGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string varClient = null;
            //var response = instance.LicenseClientGet(varClient);
            //Assert.IsType<LicenseList>(response);
        }

        /// <summary>
        /// Test LicenseClientLicenseDelete
        /// </summary>
        [Fact]
        public void LicenseClientLicenseDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string varClient = null;
            //string license = null;
            //var response = instance.LicenseClientLicenseDelete(varClient, license);
            //Assert.IsType<ApiResponse>(response);
        }

        /// <summary>
        /// Test LicenseClientLicenseGet
        /// </summary>
        [Fact]
        public void LicenseClientLicenseGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string varClient = null;
            //string? license = null;
            //var response = instance.LicenseClientLicenseGet(varClient, license);
            //Assert.IsType<LicenseList>(response);
        }

        /// <summary>
        /// Test LicenseClientLicensePost
        /// </summary>
        [Fact]
        public void LicenseClientLicensePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string varClient = null;
            //LicenseData licenseData = null;
            //string? license = null;
            //var response = instance.LicenseClientLicensePost(varClient, licenseData, license);
            //Assert.IsType<ApiResponse>(response);
        }

        /// <summary>
        /// Test LicenseClientLicensePut
        /// </summary>
        [Fact]
        public void LicenseClientLicensePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string varClient = null;
            //string body = null;
            //string? license = null;
            //var response = instance.LicenseClientLicensePut(varClient, body, license);
            //Assert.IsType<ApiResponse>(response);
        }

        /// <summary>
        /// Test LicenseGet
        /// </summary>
        [Fact]
        public void LicenseGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.LicenseGet();
            //Assert.IsType<LicenseList>(response);
        }
    }
}
