/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing ApiError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiError
        //private ApiError instance;

        public ApiErrorTests()
        {
            // TODO uncomment below to create an instance of ApiError
            //instance = new ApiError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiError
        /// </summary>
        [Fact]
        public void ApiErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiError
            //Assert.IsType<ApiError>(instance);
        }

        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Fact]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }

        /// <summary>
        /// Test the property 'ExceptionType'
        /// </summary>
        [Fact]
        public void ExceptionTypeTest()
        {
            // TODO unit test for the property 'ExceptionType'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
