/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing AuditLogEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditLogEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuditLogEntry
        //private AuditLogEntry instance;

        public AuditLogEntryTests()
        {
            // TODO uncomment below to create an instance of AuditLogEntry
            //instance = new AuditLogEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditLogEntry
        /// </summary>
        [Fact]
        public void AuditLogEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuditLogEntry
            //Assert.IsType<AuditLogEntry>(instance);
        }

        /// <summary>
        /// Test the property 'Modifiedon'
        /// </summary>
        [Fact]
        public void ModifiedonTest()
        {
            // TODO unit test for the property 'Modifiedon'
        }

        /// <summary>
        /// Test the property 'Modifiedby'
        /// </summary>
        [Fact]
        public void ModifiedbyTest()
        {
            // TODO unit test for the property 'Modifiedby'
        }
    }
}
