/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing CacheDeleteData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CacheDeleteDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CacheDeleteData
        //private CacheDeleteData instance;

        public CacheDeleteDataTests()
        {
            // TODO uncomment below to create an instance of CacheDeleteData
            //instance = new CacheDeleteData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CacheDeleteData
        /// </summary>
        [Fact]
        public void CacheDeleteDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CacheDeleteData
            //Assert.IsType<CacheDeleteData>(instance);
        }

        /// <summary>
        /// Test the property 'ColumnsDropped'
        /// </summary>
        [Fact]
        public void ColumnsDroppedTest()
        {
            // TODO unit test for the property 'ColumnsDropped'
        }

        /// <summary>
        /// Test the property 'TablesDropped'
        /// </summary>
        [Fact]
        public void TablesDroppedTest()
        {
            // TODO unit test for the property 'TablesDropped'
        }
    }
}
