/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing CacheUnusedColumn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CacheUnusedColumnTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CacheUnusedColumn
        //private CacheUnusedColumn instance;

        public CacheUnusedColumnTests()
        {
            // TODO uncomment below to create an instance of CacheUnusedColumn
            //instance = new CacheUnusedColumn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CacheUnusedColumn
        /// </summary>
        [Fact]
        public void CacheUnusedColumnInstanceTest()
        {
            // TODO uncomment below to test "IsType" CacheUnusedColumn
            //Assert.IsType<CacheUnusedColumn>(instance);
        }

        /// <summary>
        /// Test the property 'FirstReportedNotSeen'
        /// </summary>
        [Fact]
        public void FirstReportedNotSeenTest()
        {
            // TODO unit test for the property 'FirstReportedNotSeen'
        }

        /// <summary>
        /// Test the property 'ColumnName'
        /// </summary>
        [Fact]
        public void ColumnNameTest()
        {
            // TODO unit test for the property 'ColumnName'
        }
    }
}
