/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing CacheFieldType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CacheFieldTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CacheFieldType
        //private CacheFieldType instance;

        public CacheFieldTypeTests()
        {
            // TODO uncomment below to create an instance of CacheFieldType
            //instance = new CacheFieldType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CacheFieldType
        /// </summary>
        [Fact]
        public void CacheFieldTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" CacheFieldType
            //Assert.IsType<CacheFieldType>(instance);
        }
    }
}
