/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing CacheTableDirectionEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CacheTableDirectionEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CacheTableDirectionEnum
        //private CacheTableDirectionEnum instance;

        public CacheTableDirectionEnumTests()
        {
            // TODO uncomment below to create an instance of CacheTableDirectionEnum
            //instance = new CacheTableDirectionEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CacheTableDirectionEnum
        /// </summary>
        [Fact]
        public void CacheTableDirectionEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" CacheTableDirectionEnum
            //Assert.IsType<CacheTableDirectionEnum>(instance);
        }
    }
}
