/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing ClientAccessReportResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientAccessReportResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientAccessReportResponse
        //private ClientAccessReportResponse instance;

        public ClientAccessReportResponseTests()
        {
            // TODO uncomment below to create an instance of ClientAccessReportResponse
            //instance = new ClientAccessReportResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientAccessReportResponse
        /// </summary>
        [Fact]
        public void ClientAccessReportResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientAccessReportResponse
            //Assert.IsType<ClientAccessReportResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Fact]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }

        /// <summary>
        /// Test the property 'ExceptionType'
        /// </summary>
        [Fact]
        public void ExceptionTypeTest()
        {
            // TODO unit test for the property 'ExceptionType'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
