/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing ClusterPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClusterPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClusterPostRequest
        //private ClusterPostRequest instance;

        public ClusterPostRequestTests()
        {
            // TODO uncomment below to create an instance of ClusterPostRequest
            //instance = new ClusterPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClusterPostRequest
        /// </summary>
        [Fact]
        public void ClusterPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClusterPostRequest
            //Assert.IsType<ClusterPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'BootstrapVersion'
        /// </summary>
        [Fact]
        public void BootstrapVersionTest()
        {
            // TODO unit test for the property 'BootstrapVersion'
        }

        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }

        /// <summary>
        /// Test the property 'PublicIp'
        /// </summary>
        [Fact]
        public void PublicIpTest()
        {
            // TODO unit test for the property 'PublicIp'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
