/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing ClusterSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClusterSettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClusterSetting
        //private ClusterSetting instance;

        public ClusterSettingTests()
        {
            // TODO uncomment below to create an instance of ClusterSetting
            //instance = new ClusterSetting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClusterSetting
        /// </summary>
        [Fact]
        public void ClusterSettingInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClusterSetting
            //Assert.IsType<ClusterSetting>(instance);
        }

        /// <summary>
        /// Test the property 'AttributeName'
        /// </summary>
        [Fact]
        public void AttributeNameTest()
        {
            // TODO unit test for the property 'AttributeName'
        }

        /// <summary>
        /// Test the property 'AttributeValue'
        /// </summary>
        [Fact]
        public void AttributeValueTest()
        {
            // TODO unit test for the property 'AttributeValue'
        }

        /// <summary>
        /// Test the property 'CollectionName'
        /// </summary>
        [Fact]
        public void CollectionNameTest()
        {
            // TODO unit test for the property 'CollectionName'
        }
    }
}
