/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing ConsistencyReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsistencyReportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsistencyReport
        //private ConsistencyReport instance;

        public ConsistencyReportTests()
        {
            // TODO uncomment below to create an instance of ConsistencyReport
            //instance = new ConsistencyReport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsistencyReport
        /// </summary>
        [Fact]
        public void ConsistencyReportInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsistencyReport
            //Assert.IsType<ConsistencyReport>(instance);
        }

        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Fact]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }

        /// <summary>
        /// Test the property 'IsConsistent'
        /// </summary>
        [Fact]
        public void IsConsistentTest()
        {
            // TODO unit test for the property 'IsConsistent'
        }

        /// <summary>
        /// Test the property 'LocalCount'
        /// </summary>
        [Fact]
        public void LocalCountTest()
        {
            // TODO unit test for the property 'LocalCount'
        }

        /// <summary>
        /// Test the property 'RemoteCount'
        /// </summary>
        [Fact]
        public void RemoteCountTest()
        {
            // TODO unit test for the property 'RemoteCount'
        }

        /// <summary>
        /// Test the property 'MissingRemotely'
        /// </summary>
        [Fact]
        public void MissingRemotelyTest()
        {
            // TODO unit test for the property 'MissingRemotely'
        }

        /// <summary>
        /// Test the property 'MissingLocally'
        /// </summary>
        [Fact]
        public void MissingLocallyTest()
        {
            // TODO unit test for the property 'MissingLocally'
        }

        /// <summary>
        /// Test the property 'DifferentLocally'
        /// </summary>
        [Fact]
        public void DifferentLocallyTest()
        {
            // TODO unit test for the property 'DifferentLocally'
        }

        /// <summary>
        /// Test the property 'ReportedExceptions'
        /// </summary>
        [Fact]
        public void ReportedExceptionsTest()
        {
            // TODO unit test for the property 'ReportedExceptions'
        }
    }
}
