/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing CsvEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CsvEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CsvEnum
        //private CsvEnum instance;

        public CsvEnumTests()
        {
            // TODO uncomment below to create an instance of CsvEnum
            //instance = new CsvEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CsvEnum
        /// </summary>
        [Fact]
        public void CsvEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" CsvEnum
            //Assert.IsType<CsvEnum>(instance);
        }
    }
}
