/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing DestinationTarget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinationTargetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinationTarget
        //private DestinationTarget instance;

        public DestinationTargetTests()
        {
            // TODO uncomment below to create an instance of DestinationTarget
            //instance = new DestinationTarget();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinationTarget
        /// </summary>
        [Fact]
        public void DestinationTargetInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinationTarget
            //Assert.IsType<DestinationTarget>(instance);
        }

        /// <summary>
        /// Test the property 'VarDestinationtarget'
        /// </summary>
        [Fact]
        public void VarDestinationtargetTest()
        {
            // TODO unit test for the property 'VarDestinationtarget'
        }
    }
}
