/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing GlobalParameterReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GlobalParameterReportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GlobalParameterReport
        //private GlobalParameterReport instance;

        public GlobalParameterReportTests()
        {
            // TODO uncomment below to create an instance of GlobalParameterReport
            //instance = new GlobalParameterReport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GlobalParameterReport
        /// </summary>
        [Fact]
        public void GlobalParameterReportInstanceTest()
        {
            // TODO uncomment below to test "IsType" GlobalParameterReport
            //Assert.IsType<GlobalParameterReport>(instance);
        }

        /// <summary>
        /// Test the property 'VarClient'
        /// </summary>
        [Fact]
        public void VarClientTest()
        {
            // TODO unit test for the property 'VarClient'
        }

        /// <summary>
        /// Test the property 'ParamName'
        /// </summary>
        [Fact]
        public void ParamNameTest()
        {
            // TODO unit test for the property 'ParamName'
        }

        /// <summary>
        /// Test the property 'ParamValue'
        /// </summary>
        [Fact]
        public void ParamValueTest()
        {
            // TODO unit test for the property 'ParamValue'
        }

        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Fact]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }

        /// <summary>
        /// Test the property 'GlobalParam'
        /// </summary>
        [Fact]
        public void GlobalParamTest()
        {
            // TODO unit test for the property 'GlobalParam'
        }
    }
}
