/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing JsonDecoderDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonDecoderDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonDecoderDetails
        //private JsonDecoderDetails instance;

        public JsonDecoderDetailsTests()
        {
            // TODO uncomment below to create an instance of JsonDecoderDetails
            //instance = new JsonDecoderDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonDecoderDetails
        /// </summary>
        [Fact]
        public void JsonDecoderDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonDecoderDetails
            //Assert.IsType<JsonDecoderDetails>(instance);
        }

        /// <summary>
        /// Test the property 'ExpandSizeOneArrays'
        /// </summary>
        [Fact]
        public void ExpandSizeOneArraysTest()
        {
            // TODO unit test for the property 'ExpandSizeOneArrays'
        }

        /// <summary>
        /// Test the property 'FieldToDecode'
        /// </summary>
        [Fact]
        public void FieldToDecodeTest()
        {
            // TODO unit test for the property 'FieldToDecode'
        }

        /// <summary>
        /// Test the property 'StepName'
        /// </summary>
        [Fact]
        public void StepNameTest()
        {
            // TODO unit test for the property 'StepName'
        }

        /// <summary>
        /// Test the property 'Delimiter'
        /// </summary>
        [Fact]
        public void DelimiterTest()
        {
            // TODO unit test for the property 'Delimiter'
        }

        /// <summary>
        /// Test the property 'FlattenMultipleRows'
        /// </summary>
        [Fact]
        public void FlattenMultipleRowsTest()
        {
            // TODO unit test for the property 'FlattenMultipleRows'
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

        /// <summary>
        /// Test the property 'ParseAsNameValue'
        /// </summary>
        [Fact]
        public void ParseAsNameValueTest()
        {
            // TODO unit test for the property 'ParseAsNameValue'
        }
    }
}
