/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing JsonDecoderField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonDecoderFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JsonDecoderField
        //private JsonDecoderField instance;

        public JsonDecoderFieldTests()
        {
            // TODO uncomment below to create an instance of JsonDecoderField
            //instance = new JsonDecoderField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JsonDecoderField
        /// </summary>
        [Fact]
        public void JsonDecoderFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" JsonDecoderField
            //Assert.IsType<JsonDecoderField>(instance);
        }

        /// <summary>
        /// Test the property 'OutputName'
        /// </summary>
        [Fact]
        public void OutputNameTest()
        {
            // TODO unit test for the property 'OutputName'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
    }
}
