/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing LogSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogSource
        //private LogSource instance;

        public LogSourceTests()
        {
            // TODO uncomment below to create an instance of LogSource
            //instance = new LogSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogSource
        /// </summary>
        [Fact]
        public void LogSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogSource
            //Assert.IsType<LogSource>(instance);
        }
    }
}
