/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing LogsDataFields
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogsDataFieldsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogsDataFields
        //private LogsDataFields instance;

        public LogsDataFieldsTests()
        {
            // TODO uncomment below to create an instance of LogsDataFields
            //instance = new LogsDataFields();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogsDataFields
        /// </summary>
        [Fact]
        public void LogsDataFieldsInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogsDataFields
            //Assert.IsType<LogsDataFields>(instance);
        }

        /// <summary>
        /// Test the property 'Env'
        /// </summary>
        [Fact]
        public void EnvTest()
        {
            // TODO unit test for the property 'Env'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
