/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing LogsDataEcs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogsDataEcsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogsDataEcs
        //private LogsDataEcs instance;

        public LogsDataEcsTests()
        {
            // TODO uncomment below to create an instance of LogsDataEcs
            //instance = new LogsDataEcs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogsDataEcs
        /// </summary>
        [Fact]
        public void LogsDataEcsInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogsDataEcs
            //Assert.IsType<LogsDataEcs>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
