/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing QueueMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueueMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueueMessage
        //private QueueMessage instance;

        public QueueMessageTests()
        {
            // TODO uncomment below to create an instance of QueueMessage
            //instance = new QueueMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueueMessage
        /// </summary>
        [Fact]
        public void QueueMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueueMessage
            //Assert.IsType<QueueMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'SentTimestamp'
        /// </summary>
        [Fact]
        public void SentTimestampTest()
        {
            // TODO unit test for the property 'SentTimestamp'
        }

        /// <summary>
        /// Test the property 'BundleId'
        /// </summary>
        [Fact]
        public void BundleIdTest()
        {
            // TODO unit test for the property 'BundleId'
        }

        /// <summary>
        /// Test the property 'Receipt'
        /// </summary>
        [Fact]
        public void ReceiptTest()
        {
            // TODO unit test for the property 'Receipt'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Nonjsonmessage'
        /// </summary>
        [Fact]
        public void NonjsonmessageTest()
        {
            // TODO unit test for the property 'Nonjsonmessage'
        }
    }
}
