/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing RulegroupPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RulegroupPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RulegroupPostRequest
        //private RulegroupPostRequest instance;

        public RulegroupPostRequestTests()
        {
            // TODO uncomment below to create an instance of RulegroupPostRequest
            //instance = new RulegroupPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RulegroupPostRequest
        /// </summary>
        [Fact]
        public void RulegroupPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RulegroupPostRequest
            //Assert.IsType<RulegroupPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'EnableInvoke'
        /// </summary>
        [Fact]
        public void EnableInvokeTest()
        {
            // TODO unit test for the property 'EnableInvoke'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ReferencedRules'
        /// </summary>
        [Fact]
        public void ReferencedRulesTest()
        {
            // TODO unit test for the property 'ReferencedRules'
        }
    }
}
