/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing StepTypeStatisticsReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StepTypeStatisticsReportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StepTypeStatisticsReport
        //private StepTypeStatisticsReport instance;

        public StepTypeStatisticsReportTests()
        {
            // TODO uncomment below to create an instance of StepTypeStatisticsReport
            //instance = new StepTypeStatisticsReport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StepTypeStatisticsReport
        /// </summary>
        [Fact]
        public void StepTypeStatisticsReportInstanceTest()
        {
            // TODO uncomment below to test "IsType" StepTypeStatisticsReport
            //Assert.IsType<StepTypeStatisticsReport>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
