/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing SwitchCaseDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SwitchCaseDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SwitchCaseDetails
        //private SwitchCaseDetails instance;

        public SwitchCaseDetailsTests()
        {
            // TODO uncomment below to create an instance of SwitchCaseDetails
            //instance = new SwitchCaseDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SwitchCaseDetails
        /// </summary>
        [Fact]
        public void SwitchCaseDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SwitchCaseDetails
            //Assert.IsType<SwitchCaseDetails>(instance);
        }

        /// <summary>
        /// Test the property 'CaseTargets'
        /// </summary>
        [Fact]
        public void CaseTargetsTest()
        {
            // TODO unit test for the property 'CaseTargets'
        }

        /// <summary>
        /// Test the property 'StepName'
        /// </summary>
        [Fact]
        public void StepNameTest()
        {
            // TODO unit test for the property 'StepName'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'DefaultCaseTarget'
        /// </summary>
        [Fact]
        public void DefaultCaseTargetTest()
        {
            // TODO unit test for the property 'DefaultCaseTarget'
        }

        /// <summary>
        /// Test the property 'IsContains'
        /// </summary>
        [Fact]
        public void IsContainsTest()
        {
            // TODO unit test for the property 'IsContains'
        }
    }
}
