/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing TemplatePublishSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplatePublishSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplatePublishSettings
        //private TemplatePublishSettings instance;

        public TemplatePublishSettingsTests()
        {
            // TODO uncomment below to create an instance of TemplatePublishSettings
            //instance = new TemplatePublishSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplatePublishSettings
        /// </summary>
        [Fact]
        public void TemplatePublishSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplatePublishSettings
            //Assert.IsType<TemplatePublishSettings>(instance);
        }

        /// <summary>
        /// Test the property 'DetailsOfDataGrid'
        /// </summary>
        [Fact]
        public void DetailsOfDataGridTest()
        {
            // TODO unit test for the property 'DetailsOfDataGrid'
        }

        /// <summary>
        /// Test the property 'Rulename'
        /// </summary>
        [Fact]
        public void RulenameTest()
        {
            // TODO unit test for the property 'Rulename'
        }

        /// <summary>
        /// Test the property 'Rulegroups'
        /// </summary>
        [Fact]
        public void RulegroupsTest()
        {
            // TODO unit test for the property 'Rulegroups'
        }
    }
}
