/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing TestDataItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestDataItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestDataItem
        //private TestDataItem instance;

        public TestDataItemTests()
        {
            // TODO uncomment below to create an instance of TestDataItem
            //instance = new TestDataItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestDataItem
        /// </summary>
        [Fact]
        public void TestDataItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestDataItem
            //Assert.IsType<TestDataItem>(instance);
        }

        /// <summary>
        /// Test the property 'TestData'
        /// </summary>
        [Fact]
        public void TestDataTest()
        {
            // TODO unit test for the property 'TestData'
        }

        /// <summary>
        /// Test the property 'StepType'
        /// </summary>
        [Fact]
        public void StepTypeTest()
        {
            // TODO unit test for the property 'StepType'
        }
    }
}
