/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JO.Model;
using Alterian.JO.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JO.Test.Model
{
    /// <summary>
    ///  Class for testing ValidationMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidationMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidationMessage
        //private ValidationMessage instance;

        public ValidationMessageTests()
        {
            // TODO uncomment below to create an instance of ValidationMessage
            //instance = new ValidationMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidationMessage
        /// </summary>
        [Fact]
        public void ValidationMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidationMessage
            //Assert.IsType<ValidationMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'TileId'
        /// </summary>
        [Fact]
        public void TileIdTest()
        {
            // TODO unit test for the property 'TileId'
        }
    }
}
