/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// AuditLogReport
    /// </summary>
    [DataContract(Name = "AuditLogReport")]
    public partial class AuditLogReport : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditLogReport" /> class.
        /// </summary>
        /// <param name="target">target.</param>
        /// <param name="varClient">varClient.</param>
        /// <param name="name">name.</param>
        /// <param name="url">url.</param>
        /// <param name="auditlog">auditlog.</param>
        /// <param name="isrule">isrule.</param>
        public AuditLogReport(string target = default(string), string varClient = default(string), string name = default(string), string url = default(string), List<AuditLogEntry> auditlog = default(List<AuditLogEntry>), bool isrule = default(bool))
        {
            this.Target = target;
            this.VarClient = varClient;
            this.Name = name;
            this.Url = url;
            this.Auditlog = auditlog;
            this.Isrule = isrule;
        }

        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        [DataMember(Name = "target", EmitDefaultValue = false)]
        public string Target { get; set; }

        /// <summary>
        /// Gets or Sets VarClient
        /// </summary>
        [DataMember(Name = "client", EmitDefaultValue = false)]
        public string VarClient { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Auditlog
        /// </summary>
        [DataMember(Name = "auditlog", EmitDefaultValue = false)]
        public List<AuditLogEntry> Auditlog { get; set; }

        /// <summary>
        /// Gets or Sets Isrule
        /// </summary>
        [DataMember(Name = "isrule", EmitDefaultValue = true)]
        public bool Isrule { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuditLogReport {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  VarClient: ").Append(VarClient).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Auditlog: ").Append(Auditlog).Append("\n");
            sb.Append("  Isrule: ").Append(Isrule).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
