/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// CacheExecuteData
    /// </summary>
    [DataContract(Name = "CacheExecuteData")]
    public partial class CacheExecuteData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CacheExecuteData" /> class.
        /// </summary>
        /// <param name="wasApplied">wasApplied.</param>
        /// <param name="columns">columns.</param>
        /// <param name="rows">rows.</param>
        public CacheExecuteData(bool wasApplied = default(bool), List<CacheColumn> columns = default(List<CacheColumn>), List<List<string>> rows = default(List<List<string>>))
        {
            this.WasApplied = wasApplied;
            this.Columns = columns;
            this.Rows = rows;
        }

        /// <summary>
        /// Gets or Sets WasApplied
        /// </summary>
        [DataMember(Name = "wasApplied", EmitDefaultValue = true)]
        public bool WasApplied { get; set; }

        /// <summary>
        /// Gets or Sets Columns
        /// </summary>
        [DataMember(Name = "columns", EmitDefaultValue = false)]
        public List<CacheColumn> Columns { get; set; }

        /// <summary>
        /// Gets or Sets Rows
        /// </summary>
        [DataMember(Name = "rows", EmitDefaultValue = false)]
        public List<List<string>> Rows { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CacheExecuteData {\n");
            sb.Append("  WasApplied: ").Append(WasApplied).Append("\n");
            sb.Append("  Columns: ").Append(Columns).Append("\n");
            sb.Append("  Rows: ").Append(Rows).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
