/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// The consistency level of a request.
    /// </summary>
    /// <value>The consistency level of a request.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CacheConsistencyLevel
    {
        /// <summary>
        /// Enum ANY for value: ANY
        /// </summary>
        [EnumMember(Value = "ANY")]
        ANY = 1,

        /// <summary>
        /// Enum ONE for value: ONE
        /// </summary>
        [EnumMember(Value = "ONE")]
        ONE = 2,

        /// <summary>
        /// Enum TWO for value: TWO
        /// </summary>
        [EnumMember(Value = "TWO")]
        TWO = 3,

        /// <summary>
        /// Enum THREE for value: THREE
        /// </summary>
        [EnumMember(Value = "THREE")]
        THREE = 4,

        /// <summary>
        /// Enum QUORUM for value: QUORUM
        /// </summary>
        [EnumMember(Value = "QUORUM")]
        QUORUM = 5,

        /// <summary>
        /// Enum ALL for value: ALL
        /// </summary>
        [EnumMember(Value = "ALL")]
        ALL = 6,

        /// <summary>
        /// Enum LOCALONE for value: LOCAL_ONE
        /// </summary>
        [EnumMember(Value = "LOCAL_ONE")]
        LOCALONE = 7,

        /// <summary>
        /// Enum LOCALQUORUM for value: LOCAL_QUORUM
        /// </summary>
        [EnumMember(Value = "LOCAL_QUORUM")]
        LOCALQUORUM = 8,

        /// <summary>
        /// Enum EACHQUORUM for value: EACH_QUORUM
        /// </summary>
        [EnumMember(Value = "EACH_QUORUM")]
        EACHQUORUM = 9,

        /// <summary>
        /// Enum SERIAL for value: SERIAL
        /// </summary>
        [EnumMember(Value = "SERIAL")]
        SERIAL = 10,

        /// <summary>
        /// Enum LOCALSERIA for value: LOCAL_SERIA
        /// </summary>
        [EnumMember(Value = "LOCAL_SERIA")]
        LOCALSERIA = 11
    }

}
