/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// ConversationUsageReport
    /// </summary>
    [DataContract(Name = "ConversationUsageReport")]
    public partial class ConversationUsageReport : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConversationUsageReport" /> class.
        /// </summary>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="conversations">conversations.</param>
        /// <param name="activeConversations">activeConversations.</param>
        /// <param name="bulkLoads">bulkLoads.</param>
        public ConversationUsageReport(string timestamp = default(string), int conversations = default(int), int activeConversations = default(int), int bulkLoads = default(int))
        {
            this.Timestamp = timestamp;
            this.Conversations = conversations;
            this.ActiveConversations = activeConversations;
            this.BulkLoads = bulkLoads;
        }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name = "timestamp", EmitDefaultValue = false)]
        public string Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets Conversations
        /// </summary>
        [DataMember(Name = "conversations", EmitDefaultValue = false)]
        public int Conversations { get; set; }

        /// <summary>
        /// Gets or Sets ActiveConversations
        /// </summary>
        [DataMember(Name = "activeConversations", EmitDefaultValue = false)]
        public int ActiveConversations { get; set; }

        /// <summary>
        /// Gets or Sets BulkLoads
        /// </summary>
        [DataMember(Name = "bulkLoads", EmitDefaultValue = false)]
        public int BulkLoads { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConversationUsageReport {\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Conversations: ").Append(Conversations).Append("\n");
            sb.Append("  ActiveConversations: ").Append(ActiveConversations).Append("\n");
            sb.Append("  BulkLoads: ").Append(BulkLoads).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
