/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// Defines logType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LogType
    {
        /// <summary>
        /// Enum Writetolog for value: writetolog
        /// </summary>
        [EnumMember(Value = "writetolog")]
        Writetolog = 1,

        /// <summary>
        /// Enum System for value: system
        /// </summary>
        [EnumMember(Value = "system")]
        System = 2,

        /// <summary>
        /// Enum Writetologandsystem for value: writetologandsystem
        /// </summary>
        [EnumMember(Value = "writetologandsystem")]
        Writetologandsystem = 3
    }

}
