/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// Defines QueueBackendEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum QueueBackendEnum
    {
        /// <summary>
        /// Enum Sqs for value: sqs
        /// </summary>
        [EnumMember(Value = "sqs")]
        Sqs = 1,

        /// <summary>
        /// Enum Rabbit for value: rabbit
        /// </summary>
        [EnumMember(Value = "rabbit")]
        Rabbit = 2
    }

}
