/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// Role
    /// </summary>
    [DataContract(Name = "role")]
    public partial class Role : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Role" /> class.
        /// </summary>
        /// <param name="lastModifiedDate">When was this object last modified? Timestamp in ISO-8601 format.</param>
        /// <param name="lastModifiedUser">What is the name of the user who last modified this object?.</param>
        /// <param name="name">The unique name of this role.</param>
        /// <param name="varSystem">Is this a system role?.</param>
        /// <param name="clients">clients.</param>
        /// <param name="permissions">The names of the permissions that a user will be granted if they have this role.</param>
        public Role(string lastModifiedDate = default(string), string lastModifiedUser = default(string), string name = default(string), bool varSystem = default(bool), List<string> clients = default(List<string>), List<string> permissions = default(List<string>))
        {
            this.LastModifiedDate = lastModifiedDate;
            this.LastModifiedUser = lastModifiedUser;
            this.Name = name;
            this.VarSystem = varSystem;
            this.Clients = clients;
            this.Permissions = permissions;
        }

        /// <summary>
        /// When was this object last modified? Timestamp in ISO-8601 format
        /// </summary>
        /// <value>When was this object last modified? Timestamp in ISO-8601 format</value>
        [DataMember(Name = "lastModifiedDate", EmitDefaultValue = false)]
        public string LastModifiedDate { get; set; }

        /// <summary>
        /// What is the name of the user who last modified this object?
        /// </summary>
        /// <value>What is the name of the user who last modified this object?</value>
        [DataMember(Name = "lastModifiedUser", EmitDefaultValue = false)]
        public string LastModifiedUser { get; set; }

        /// <summary>
        /// The unique name of this role
        /// </summary>
        /// <value>The unique name of this role</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Is this a system role?
        /// </summary>
        /// <value>Is this a system role?</value>
        [DataMember(Name = "system", EmitDefaultValue = true)]
        public bool VarSystem { get; set; }

        /// <summary>
        /// Gets or Sets Clients
        /// </summary>
        [DataMember(Name = "clients", EmitDefaultValue = false)]
        public List<string> Clients { get; set; }

        /// <summary>
        /// The names of the permissions that a user will be granted if they have this role
        /// </summary>
        /// <value>The names of the permissions that a user will be granted if they have this role</value>
        [DataMember(Name = "permissions", EmitDefaultValue = false)]
        public List<string> Permissions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Role {\n");
            sb.Append("  LastModifiedDate: ").Append(LastModifiedDate).Append("\n");
            sb.Append("  LastModifiedUser: ").Append(LastModifiedUser).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  VarSystem: ").Append(VarSystem).Append("\n");
            sb.Append("  Clients: ").Append(Clients).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
