/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// The type of the Cache table
    /// </summary>
    /// <value>The type of the Cache table</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TableTypeEnum
    {
        /// <summary>
        /// Enum Normal for value: normal
        /// </summary>
        [EnumMember(Value = "normal")]
        Normal = 1,

        /// <summary>
        /// Enum Fieldvalue for value: fieldvalue
        /// </summary>
        [EnumMember(Value = "fieldvalue")]
        Fieldvalue = 2,

        /// <summary>
        /// Enum Futureevent for value: futureevent
        /// </summary>
        [EnumMember(Value = "futureevent")]
        Futureevent = 3
    }

}
