/*
 * Journey Orchestration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JO.Client.OpenAPIDateConverter;

namespace Alterian.JO.Model
{
    /// <summary>
    /// TemplatePublishSettings
    /// </summary>
    [DataContract(Name = "TemplatePublishSettings")]
    public partial class TemplatePublishSettings : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatePublishSettings" /> class.
        /// </summary>
        /// <param name="detailsOfDataGrid">detailsOfDataGrid.</param>
        /// <param name="rulename">rulename.</param>
        /// <param name="rulegroups">rulegroups.</param>
        public TemplatePublishSettings(DataGridDetails detailsOfDataGrid = default(DataGridDetails), string rulename = default(string), List<string> rulegroups = default(List<string>))
        {
            this.DetailsOfDataGrid = detailsOfDataGrid;
            this.Rulename = rulename;
            this.Rulegroups = rulegroups;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets DetailsOfDataGrid
        /// </summary>
        [DataMember(Name = "detailsOfDataGrid", EmitDefaultValue = false)]
        public DataGridDetails DetailsOfDataGrid { get; set; }

        /// <summary>
        /// Gets or Sets Rulename
        /// </summary>
        [DataMember(Name = "rulename", EmitDefaultValue = false)]
        public string Rulename { get; set; }

        /// <summary>
        /// Gets or Sets Rulegroups
        /// </summary>
        [DataMember(Name = "rulegroups", EmitDefaultValue = false)]
        public List<string> Rulegroups { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplatePublishSettings {\n");
            sb.Append("  DetailsOfDataGrid: ").Append(DetailsOfDataGrid).Append("\n");
            sb.Append("  Rulename: ").Append(Rulename).Append("\n");
            sb.Append("  Rulegroups: ").Append(Rulegroups).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
